// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					ChassisPowerstate: ChassisPowerstateConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []ChassisPowerstateAttributeKey{ChassisPowerstateAttributeKeyChassisID, ChassisPowerstateAttributeKeyChassisAssetTag, ChassisPowerstateAttributeKeyChassisModel, ChassisPowerstateAttributeKeyChassisName, ChassisPowerstateAttributeKeyChassisManufacturer, ChassisPowerstateAttributeKeyChassisSerialNumber, ChassisPowerstateAttributeKeyChassisSku, ChassisPowerstateAttributeKeyChassisChassisType},
					},
					ChassisStatusHealth: ChassisStatusHealthConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []ChassisStatusHealthAttributeKey{ChassisStatusHealthAttributeKeyChassisID, ChassisStatusHealthAttributeKeyChassisAssetTag, ChassisStatusHealthAttributeKeyChassisModel, ChassisStatusHealthAttributeKeyChassisName, ChassisStatusHealthAttributeKeyChassisManufacturer, ChassisStatusHealthAttributeKeyChassisSerialNumber, ChassisStatusHealthAttributeKeyChassisSku, ChassisStatusHealthAttributeKeyChassisChassisType},
					},
					ChassisStatusState: ChassisStatusStateConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []ChassisStatusStateAttributeKey{ChassisStatusStateAttributeKeyChassisID, ChassisStatusStateAttributeKeyChassisAssetTag, ChassisStatusStateAttributeKeyChassisModel, ChassisStatusStateAttributeKeyChassisName, ChassisStatusStateAttributeKeyChassisManufacturer, ChassisStatusStateAttributeKeyChassisSerialNumber, ChassisStatusStateAttributeKeyChassisSku, ChassisStatusStateAttributeKeyChassisChassisType},
					},
					FanReading: FanReadingConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FanReadingAttributeKey{FanReadingAttributeKeyChassisID, FanReadingAttributeKeyFanName, FanReadingAttributeKeyFanReadingUnits},
					},
					FanStatusHealth: FanStatusHealthConfig{
						Enabled: true,
					},
					FanStatusState: FanStatusStateConfig{
						Enabled: true,
					},
					SystemPowerstate: SystemPowerstateConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemPowerstateAttributeKey{SystemPowerstateAttributeKeySystemID, SystemPowerstateAttributeKeySystemAssetTag, SystemPowerstateAttributeKeySystemBiosVersion, SystemPowerstateAttributeKeySystemModel, SystemPowerstateAttributeKeySystemName, SystemPowerstateAttributeKeySystemManufacturer, SystemPowerstateAttributeKeySystemSerialNumber, SystemPowerstateAttributeKeySystemSku, SystemPowerstateAttributeKeySystemSystemType},
					},
					SystemStatusHealth: SystemStatusHealthConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemStatusHealthAttributeKey{SystemStatusHealthAttributeKeySystemID, SystemStatusHealthAttributeKeySystemAssetTag, SystemStatusHealthAttributeKeySystemBiosVersion, SystemStatusHealthAttributeKeySystemModel, SystemStatusHealthAttributeKeySystemName, SystemStatusHealthAttributeKeySystemManufacturer, SystemStatusHealthAttributeKeySystemSerialNumber, SystemStatusHealthAttributeKeySystemSku, SystemStatusHealthAttributeKeySystemSystemType},
					},
					SystemStatusState: SystemStatusStateConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemStatusStateAttributeKey{SystemStatusStateAttributeKeySystemID, SystemStatusStateAttributeKeySystemAssetTag, SystemStatusStateAttributeKeySystemBiosVersion, SystemStatusStateAttributeKeySystemModel, SystemStatusStateAttributeKeySystemName, SystemStatusStateAttributeKeySystemManufacturer, SystemStatusStateAttributeKeySystemSerialNumber, SystemStatusStateAttributeKeySystemSku, SystemStatusStateAttributeKeySystemSystemType},
					},
					TemperatureReading: TemperatureReadingConfig{
						Enabled: true,
					},
					TemperatureStatusHealth: TemperatureStatusHealthConfig{
						Enabled: true,
					},
					TemperatureStatusState: TemperatureStatusStateConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostName: ResourceAttributeConfig{Enabled: true},
					URLFull:  ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					ChassisPowerstate: ChassisPowerstateConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []ChassisPowerstateAttributeKey{ChassisPowerstateAttributeKeyChassisID, ChassisPowerstateAttributeKeyChassisAssetTag, ChassisPowerstateAttributeKeyChassisModel, ChassisPowerstateAttributeKeyChassisName, ChassisPowerstateAttributeKeyChassisManufacturer, ChassisPowerstateAttributeKeyChassisSerialNumber, ChassisPowerstateAttributeKeyChassisSku, ChassisPowerstateAttributeKeyChassisChassisType},
					},
					ChassisStatusHealth: ChassisStatusHealthConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []ChassisStatusHealthAttributeKey{ChassisStatusHealthAttributeKeyChassisID, ChassisStatusHealthAttributeKeyChassisAssetTag, ChassisStatusHealthAttributeKeyChassisModel, ChassisStatusHealthAttributeKeyChassisName, ChassisStatusHealthAttributeKeyChassisManufacturer, ChassisStatusHealthAttributeKeyChassisSerialNumber, ChassisStatusHealthAttributeKeyChassisSku, ChassisStatusHealthAttributeKeyChassisChassisType},
					},
					ChassisStatusState: ChassisStatusStateConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []ChassisStatusStateAttributeKey{ChassisStatusStateAttributeKeyChassisID, ChassisStatusStateAttributeKeyChassisAssetTag, ChassisStatusStateAttributeKeyChassisModel, ChassisStatusStateAttributeKeyChassisName, ChassisStatusStateAttributeKeyChassisManufacturer, ChassisStatusStateAttributeKeyChassisSerialNumber, ChassisStatusStateAttributeKeyChassisSku, ChassisStatusStateAttributeKeyChassisChassisType},
					},
					FanReading: FanReadingConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FanReadingAttributeKey{FanReadingAttributeKeyChassisID, FanReadingAttributeKeyFanName, FanReadingAttributeKeyFanReadingUnits},
					},
					FanStatusHealth: FanStatusHealthConfig{
						Enabled: false,
					},
					FanStatusState: FanStatusStateConfig{
						Enabled: false,
					},
					SystemPowerstate: SystemPowerstateConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemPowerstateAttributeKey{SystemPowerstateAttributeKeySystemID, SystemPowerstateAttributeKeySystemAssetTag, SystemPowerstateAttributeKeySystemBiosVersion, SystemPowerstateAttributeKeySystemModel, SystemPowerstateAttributeKeySystemName, SystemPowerstateAttributeKeySystemManufacturer, SystemPowerstateAttributeKeySystemSerialNumber, SystemPowerstateAttributeKeySystemSku, SystemPowerstateAttributeKeySystemSystemType},
					},
					SystemStatusHealth: SystemStatusHealthConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemStatusHealthAttributeKey{SystemStatusHealthAttributeKeySystemID, SystemStatusHealthAttributeKeySystemAssetTag, SystemStatusHealthAttributeKeySystemBiosVersion, SystemStatusHealthAttributeKeySystemModel, SystemStatusHealthAttributeKeySystemName, SystemStatusHealthAttributeKeySystemManufacturer, SystemStatusHealthAttributeKeySystemSerialNumber, SystemStatusHealthAttributeKeySystemSku, SystemStatusHealthAttributeKeySystemSystemType},
					},
					SystemStatusState: SystemStatusStateConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SystemStatusStateAttributeKey{SystemStatusStateAttributeKeySystemID, SystemStatusStateAttributeKeySystemAssetTag, SystemStatusStateAttributeKeySystemBiosVersion, SystemStatusStateAttributeKeySystemModel, SystemStatusStateAttributeKeySystemName, SystemStatusStateAttributeKeySystemManufacturer, SystemStatusStateAttributeKeySystemSerialNumber, SystemStatusStateAttributeKeySystemSku, SystemStatusStateAttributeKeySystemSystemType},
					},
					TemperatureReading: TemperatureReadingConfig{
						Enabled: false,
					},
					TemperatureStatusHealth: TemperatureStatusHealthConfig{
						Enabled: false,
					},
					TemperatureStatusState: TemperatureStatusStateConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostName: ResourceAttributeConfig{Enabled: false},
					URLFull:  ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ChassisPowerstateConfig{}, ChassisStatusHealthConfig{}, ChassisStatusStateConfig{}, FanReadingConfig{}, FanStatusHealthConfig{}, FanStatusStateConfig{}, SystemPowerstateConfig{}, SystemStatusHealthConfig{}, SystemStatusStateConfig{}, TemperatureReadingConfig{}, TemperatureStatusHealthConfig{}, TemperatureStatusStateConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				HostName: ResourceAttributeConfig{Enabled: true},
				URLFull:  ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				HostName: ResourceAttributeConfig{Enabled: false},
				URLFull:  ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
